import { makeStyles } from "@material-ui/core";

const useStyles = makeStyles((theme) => ({
    header: {
        direction: "rtl",
        position: "fixed",
        left: 0,
        top: 0,
        width: "100%",
        height: "auto",
        zIndex: 10,
        margin: "0 auto",
        backgroundColor: "#ffff",
        boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
    },
    container: {
        maxWidth: "99rem",
        height: "auto",
        margin: "0 auto",
        padding: "0 1.25rem",
    },
    navbar: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "flex-start",
        columnGap: "7rem",
        width: "100%",
        height: "4rem",
        margin: "0 auto",
    },
    burger: {
        position: "relative",
        display: "block",
        cursor: "pointer",
        order: -1,
        width: "1.6rem",
        height: "auto",
        border: "none",
        outline: "none",
        visibility: "visible",
        [theme.breakpoints.up('md')]: {
            display: "none",
            visibility: "hidden",
        },
    },
    burgerLine: {
        display: "block",
        cursor: "pointer",
        width: "100%",
        height: "2px",
        margin: "6px auto",
        transform: "rotate(0deg)",
        background: "#1a1a1a",
    },
    overlay: {
        position: "fixed",
        top: 0,
        left: 0,
        width: "100%",
        height: "100%",
        zIndex: 10,
        opacity: 0,
        visibility: "hidden",
        backgroundColor: "rgba(0, 0, 0, 0.65)",
        transition: "all 0.3s ease-in-out",
        '&.overlayisactive': {
            display: "block",
            opacity: 1,
            visibility: "visible",
        },
    },
    menu: {
        position: "fixed",
        top: 0,
        left: "-100%",
        width: "80%",
        height: "100%",
        zIndex: 10,
        overflowY: "auto",
        backgroundColor: "#ffff",
        boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
        transition: "all 0.45s ease-in-out",
        '&.menuisactive': {
            top: 0,
            left: 0,
        },
        [theme.breakpoints.up('md')]: {
            position: "relative",
            top: 0,
            left: 0,
            width: "auto",
            height: "auto",
            marginLeft: "auto",
            background: "none",
            boxShadow: "none",
        },
    },
    menuInner: {
        display: "flex",
        flexDirection: "column",
        margin: "1.25rem",
        [theme.breakpoints.up('md')]: {
            flexDirection: "row",
            columnGap: "6rem",
            margin: "0 auto",
        },
    },
    menuLink: {
        fontFamily: "inherit",
        fontSize: "1rem",
        fontWeight: 500,
        lineHeight: 1.5,
        textTransform: "uppercase",
        color: "#1a1a1a",
        transition: "all 0.3s ease",
        [theme.breakpoints.up('md')]: {
            textTransform: "capitalize",
        },
    },
    menuBlock: {
        display: "inline-block",
        fontFamily: "inherit",
        fontWeight: 500,
        lineHeight: 1.25,
        userSelect: "none",
        textAlign: "center",
        whiteSpace: "nowrap",
        marginLeft: "auto",
        padding: "0.65rem 1.5rem",
        borderRadius: "3rem",
        color: "#ffff",
        backgroundColor: "#596AF8",
        transition: "all 0.3s ease-in-out",
        [theme.breakpoints.up('md')]: {
            marginLeft: "2rem",
        },
    },
    auth:{
        width:"240px",
        display:"flex",
        alignItems:"center",
        justifyContent:"flex-start",
        columnGap:"2rem"

    }
}));

export default useStyles;
