"use client"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SiteLayout from '@/src/shared/components/layouts/site-layout'
import { useEffect } from 'react'
import useUser from '@/src/hooks/useUser'
import { usePathname } from 'next/navigation'
import { useRouter } from 'next/navigation'
import PanelLayout from '@/src/shared/components/layouts/panel/panel-lauout'
import Script from 'next/script'


// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {









  const pathname = usePathname()



  // useEffect(() => {

  //   const goLogin=()=>{
  //     if (pathname !== "/" && pathname !== "/auth/login" && pathname !== "/auth/register") {
  //       router.replace("/auth/login")
  //     }
  //   }
  //   user
  //       .refresh()
    
  //       .catch(() => {
     
  //         goLogin();
  //       })
  //       .finally(() => {
  //         // setIsLoading(false);
  //       });
  // },[pathname]);


  const isDashboardRoute = pathname.startsWith('/dashboard');




  return (
    <>
      <Script
        src="/scripts/bot.js"
        id="myScript"
        nonce="XUENAJFW"
        defer
        data-token="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJwbG90c2V0MSIsImJvdElkIjoicGxvdHNldDEiLCJpYXQiOjE3MTQ5MDA3MDYsImV4cCI6MTcxNDk4MTcwNn0.xnHuwkxVFeHmcZYKWZ_zQXxo1zntk9Dj5X1oJ8cv1-I"
      />
      
      {isDashboardRoute ? (
       <PanelLayout>
         {children}
       </PanelLayout>
      ) : (
        <SiteLayout>
          {children}
        </SiteLayout>
      )}
    </>
  );
  
  

}
